name: Create Cloud Storage Bucket

on:
  push:
    branches: [main]

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Create Cloud Storage Bucket
      run: |
        gsutil mb -l us-central1 gs://githubactionwithgcp

