name: Create Cloud Storage Bucket

on:
  push:
    branches: [main]

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with gcloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp.json
          gcloud auth activate-service-account --key-file=gcp.json
          rm gcp.json
      - name: Create Cloud Storage Bucket
        run: |
          gsutil mb -l us-central1 gs://githubactionwithgcp
